# Generated by Django 5.0.3 on 2024-05-22 22:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lectivo', models.CharField(max_length=50)),
                ('n_processo', models.CharField(max_length=70)),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.PositiveIntegerField()),
                ('data_nascimento', models.DateField()),
                ('n_bi', models.CharField(max_length=80)),
                ('data_emissao', models.DateField()),
                ('foto', models.ImageField(upload_to='imagens_aluno/')),
                ('estado_civil', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(max_length=255)),
                ('nome_mae', models.CharField(max_length=255)),
                ('profissao_pai', models.CharField(max_length=150)),
                ('profissao_mae', models.CharField(max_length=150)),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Iniciação', 'Iniciação'), ('1ª', '1ª'), ('2ª', '2ª'), ('3ª', '3ª'), ('4ª', '4ª'), ('5ª', '5ª'), ('6ª', '6ª'), ('7ª', '7ª'), ('8ª', '8ª'), ('9ª', '9ª'), ('10ª', '10ª'), ('11ª', '11ª'), ('12ª', '12ª'), ('13ª', '13ª')], max_length=55)),
                ('nivel', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('objectivo', models.TextField()),
                ('programa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('programa', models.TextField()),
                ('objectivo', models.TextField()),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('bi', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('nivel_escolaridade', models.CharField(max_length=100)),
                ('habilitacoes', models.TextField()),
                ('experiencia', models.TextField()),
                ('estado_civil', models.CharField(max_length=70)),
                ('foto', models.ImageField(null=True, upload_to='imagens_professor/')),
                ('genero', models.CharField(max_length=40)),
                ('nacionalidade', models.CharField(max_length=60)),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_professor', models.BooleanField(default=False, verbose_name='Is professor')),
                ('is_aluno', models.BooleanField(default=False, verbose_name='Is aluno')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CursoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classe')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.curso')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classe')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prova', models.CharField(choices=[('Escrita', 'Escrita'), ('Oral', 'Oral'), ('Pratica', 'Pratica'), ('Defesa_trabalho', 'Defesa_trabalho')], max_length=50)),
                ('valor', models.FloatField()),
                ('data_prova', models.DateField()),
                ('trimestre', models.CharField(max_length=90)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('n_alunos', models.PositiveIntegerField()),
                ('n_max_alunos', models.PositiveIntegerField()),
                ('sala', models.CharField(max_length=50)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classe')),
                ('curso_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.curso')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classe')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
        ),
    ]
