# Generated by Django 5.0.3 on 2024-06-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_medianota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='trimestre',
            field=models.CharField(choices=[('Primeiro trimeste', 'Primeiro trimestre'), ('Segundo trimeste', 'Segundo trimestre'), ('Terceiro trimeste', 'Terceiro trimestre')], max_length=90),
        ),
    ]
