# Generated by Django 5.0.3 on 2024-06-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_nota_trimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='classe_id',
        ),
    ]
