# Generated by Django 5.0.3 on 2024-06-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_matricula_classe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(choices=[('Solterio', 'Solteiro'), ('Casado', 'Casado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='estado_civil',
            field=models.CharField(choices=[('Solterio', 'Solteiro'), ('Casado', 'Casado')], max_length=70),
        ),
        migrations.AlterField(
            model_name='professor',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=40),
        ),
    ]
